# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Hack N Cheese
tagline:          'Cheezy hacks'
description:      'Stuff I hack about: raspberry pi, home automation, linux, web apps'
url:              http://www.hackncheese.com

author:
  name:           'Sylvain Emery'
  url:            https://plus.google.com/+SylvainEmery

paginate:         5

# Custom vars
version:          0.0.1

github:
  url:           https://github.com/sylvainemery/