# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

exclude:          ['*.sublime-*', 'LICENSE.md', 'README.md']

# Setup
title:            Hack N Cheese
tagline:          'Cheezy hacks'
description:      'Stuff I hack about: raspberry pi, home automation, linux, web apps'
url:              http://hackncheese.com

author:
  name:           'Sylvain Emery'

paginate:         5
